name: llm_lab_sdk_flutter
description: "An SDK for integrating your LLM Lab AI Agent"

version: 1.1.0
homepage: https://github.com/intelligent-iterations/llm_lab_sdk_flutter
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  either_dart: ^1.0.0
  fetch_client: ^1.0.2
  llm_chat: ^1.0.0+1
  http: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

